# Project information
site_name: ""
site_description: "Zero trust Runtime Kubernetes security"
site_author: "Ravi Kishor"
site_url: "https://accuknox.com/"
# Copyright
copyright: "&copy; 2023 AccuKnox. All Rights Reserved."
# Repository
repo_name: "GitHub"
repo_url: "https://github.com/kubearmor/KubeArmor"
edit_uri: "https://github.com/accuknox/help-test/edit/main/docs"
# Configuration
docs_dir: "docs"
dev_addr: '127.0.0.1:80'
theme:
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      #primary: indigo
      #accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  logo: 'assets/images/ak-logo.png'
  favicon: 'assets/images/favicon.ico'
  hide:
  - toc

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - redirects:
        redirect_maps:
            'index.md': 'overview/cnapp-definition.md'
# Customization
extra_javascript:
# - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
- "assets/stylesheets/style.css"
extra:
  analytics:
    provider: google
    property: G-QP9CWLWH0P
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/accuknox"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/AccuKnox"

# Page tree
pages:


nav:
  - "Overview":
    - "CNAPP Definition" : "overview/cnapp-definition.md"
    - "Need for CNAPP & Architecture" : "overview/need-for-cnapp-and-arch.md"
    - "Defining Runtime security & Static Security" : "overview/defining-runtime-security-and-static-security.md"
    - "What is CSPM?" : "overview/what-is-cspm.md"
    - "What is CWPP?" : "overview/what-is-cwpp.md"
    - "Open source vs Enterprise" : "overview/open-source-vs-enterprise.md"

  - "AccuKnox SaaS":
    - "Dashboard" : "saas/dashboard.md"
    - "Inventory" : 
          - "Assets": "saas/assets.md"
          - "Cloud Workloads" : "saas/cloud-workloads.md"
          - "Imports" : "saas/imports.md"
          - "Explorer" : "saas/explorer.md"
          - "Baselines" : "saas/inventory-baseline.md"
    - "Issues" :
          - "Vulnerabilities" : "saas/vulnerabilities.md"
          - "Registry Scan" : "saas/registry-scan.md"
          - "Risk-based Prioritization" : "saas/risk-based-prioritization.md"
    - "Compliance" : 
          - "Baselines" : "saas/baselines.md"
          - "CSPM Executive Dashboard" : "saas/cspm-executive-dashboard.md"
    - "Runtime Protection" : 
          - "CWPP Dashboard" : "saas/cwpp-dashboard.md"
          - "App Behavior" : "saas/app-behavior.md"
          - "Policies" : "saas/policies.md"
    - "Remediation" : 
          - "Ticket Summary" : "saas/ticket-summary.md"
    - "Monitors/Logging" : 
          - "Logs" : "saas/logs.md"
          - "Triggers" : "saas/triggers.md"
          - "Monitors" : "saas/monitors.md"
    - "Reports" : "saas/reports.md"
    - "Notification" : 
         - "Slack" : "saas/slack.md"
         - "Email" : "saas/email.md" 
    - "Settings" : 
          - "Cloud Accounts" : "saas/cloud-accounts.md"
          - "Manage Cluster" : "saas/manage-cluster.md"
          - "User Management" : "saas/user-management.md"
          - "RBAC" : "saas/rbac.md"
          - "Integrations" : "saas/integrations.md"
          - "Labels" : "saas/labels.md"
          - "Tags" : "saas/tags.md"
          - "Groups" : "saas/groups.md"
          - "Ticket Template" : "saas/ticket-template.md"

  - "Getting Started":
    - "Open Source Installation": "getting-started/open-source.md"
    - "Prerequisites" : 
        - "CWPP Prerequisites": "getting-started/cwpp-prereq.md"
        - "CSPM Prerequisites": "getting-started/cspm-prereq.md"
    - "AccuKnox Agents" : "getting-started/accuknox-agents.md"
    - "Cloud Onboarding" : "getting-started/cloud-onboarding.md"
    - "Cluster Onboarding" : "getting-started/cluster-onboarding.md"
    - "On-prem-Installation Guide" : "getting-started/on-prem-installation-guide.md"
    - "Release Notes":
        - "AccuKnox" : "getting-started/accuknox.md"
        - "KubeArmor" : "getting-started/kubearmor.md"
    - "Support Matrix":
        - "KubeArmor Support Matrix" : "getting-started/kubearmor-support-matrix.md"
        - "Public Cloud" : "getting-started/public-cloud.md"
        - "Private Cloud" : "getting-started/private-cloud.md"
        - "VMs" : "getting-started/vms.md"
        - "Supported Benchmarks" : "getting-started/supported-benchmarks.md"
        - "Assets list" : "getting-started/assets-list.md" 

  - "Integrations":
     - "Ticketing" :
         - "Jira cloud" : "integrations/jira-cloud-cwpp.md"
         - "Jira Server" : "integrations/jira-server-cspm.md"
         - "Freshservice" : "integrations/freshservice-cspm.md"
     - "SIEM/ Security Events" : 
         - "Splunk" : "integrations/splunk.md"
         - "AWS Cloudwatch" : "integrations/aws-cloudwatch.md"
         - "Rsyslog" : "integrations/rsyslog.md"
     - "Forwarding events for Splunk App" : "integrations/accuKnox-splunk-app-installation-configuration.md"
     - "Rsyslog feeder integration": "integrations/rsyslog_feeder_integration.md"
  - "Use-Cases":
    - "Vulnerability Management" : "use-cases/vulnerability.md"
    - "Cloud Misconfiguration and Drift Detection" : "use-cases/cloud-misconfigurations.md"
    - "Container Security" :
      - "Image Scan": "use-cases/image-scan.md" 
    - "Asset Inventory" : "use-cases/asset-inventory.md"
    - "Application Behavior Modeling": "use-cases/app-behavior.md"
    - "Application Hardening" : "use-cases/app-hardening.md"
    - "Network Segmentation" : "use-cases/network-segmentation.md"
    - "5G, Edge Workload Security" : "use-cases/5g-edge-workload-security.md"
    - "HashiCorp Vault Hardening" : "use-cases/hashicorp.md"
    - "Protect Sample Workloads" :
      - "WordPress-MySQL Application": "use-cases/wordpress-mysql.md" 
      - "DVWA Application": "use-cases/dvwa.md"  
      - "PHP-MySQL Application": "use-cases/php-mysql.md"
  
  - "Troubleshooting & FAQs":
    - "FAQs" : "faqs/troubleshooting-and-faqs.md"

