# Project information
site_name: ""
site_description: "Zero trust CNAPP"
site_author: "AccuKnox"
site_url: "https://help.accuknox.com/"
# Copyright
copyright: "&copy; 2024 AccuKnox. All Rights Reserved."
# Repository
repo_name: "GitHub"
repo_url: "https://github.com/kubearmor/KubeArmor"
edit_uri: "https://github.com/accuknox/help-test/edit/main/docs"
# Configuration
docs_dir: "docs"
dev_addr: '127.0.0.1:8000'
theme:
  name: "material"
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      # accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  font:
    text: 'Montserrat'
    code: 'Fira Code'
  #icon:
  #logo: 'assets/images/logo-black.png'
  logo_dark_mode: 'assets/images/logo-white.png'
  logo_light_mode: 'assets/images/logo-white.png'
  # logo_light_mode: 'assets/images/logo-black.png' [REVERT IF NEEDED]
  favicon: 'assets/images/favicon.ico'
  # hide:
  # - toc

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - abbr
  - tables
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      toc_depth: "1-1"
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - neoteroi.cards
plugins:
  - external-markdown
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - redirects:
        redirect_maps:
            'index.md': 'introduction/accuknox-architecture.md'
# Customization
#extra_javascript:
# - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
- "assets/stylesheets/style.css"
- "assets/stylesheets/extra.css"
- "assets/stylesheets/neoteroi-mkdocs.css"
extra:
  analytics:
    provider: google
    property: G-QP9CWLWH0P
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/accuknox"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/AccuKnox"
    - icon: "fontawesome/brands/slack"
      link: "https://kubearmor.slack.com/join/shared_invite/zt-1ltmqdbc6-rSHw~LM6MesZZasmP2hAcA#/shared-invite/email"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/accuknox/?original_referer=https%3A%2F%2Fwww.accuknox.com%2F"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCLqK0vGQTa2ctjnbNzvP52Q"
# Page tree
pages:


nav:
  - "Getting Started":
    - "AccuKnox Architecture (Enterprise CNAPP Suite)" : "introduction/accuknox-architecture.md"
    - "Deployment Models" :
      - "Deployment Models": "getting-started/deployment-models.md"
      - "CWPP Prerequisites": "getting-started/cwpp-prereq.md"
      - "On-prem Installation" : "getting-started/on-prem-installation-guide.md"
      - "DevSecOps" : "getting-started/devsecops.md"
    - "AccuKnox Agents" : "getting-started/accuknox-agents.md"
    - "Release Notes":
        - "AccuKnox" :
           - "V2.0 Release Notes" : "getting-started/2.0-release.md"
           - "V1.7 Release Notes" : "getting-started/1-7-release.md"
           - "v1.6 Release Notes" : "getting-started/1-6-release.md"
           - "v1.5 Release Notes" : "getting-started/1-5-release.md"
        - "KubeArmor" : "getting-started/kubearmor-release.md"
    - "Open Source":
      - "Open source vs Enterprise" : "introduction/open-source-vs-enterprise.md"
      - "Open Source Installation": "getting-started/open-source.md"
    - "Sample Workloads Protection" :
      - "WordPress-MySQL": "getting-started/wordpress-mysql.md"
      - "DVWA": "getting-started/dvwa.md"
      - "PHP-MySQL": "getting-started/php-mysql.md"
  - "How To":
    - "CSPM Prerequisites":
          - "AWS": "how-to/cspm-prereq-aws.md"
          - "Azure": "how-to/cspm-prereq-azure.md"
          - "GCP": "how-to/cspm-prereq-gcp.md"
    - "Onboard Cloud Account" :
      - "AWS" : "how-to/aws-onboarding.md"
      - "Azure" : "how-to/azure-onboarding.md"
      - "GCP" : "how-to/gcp-onboarding.md"
    - "Onboard Cluster" :
      - "Cluster Onboarding" : "how-to/cluster-onboarding.md"
      - "Cluster Miconfiguration Scan Onboarding" : "how-to/cluster-misconfig-scan-onboarding.md"
      - "Cluster Offboarding" : "how-to/cluster-offboarding.md"
    - "Onboard Registry":
      - "ACR": "how-to/acr.md"
      - "ECR": "how-to/ecr.md"
      - "GAR": "how-to/gar.md"
      - "Harbor": "how-to/harbor.md"
    - "Onboard VM" :
      - "SystemD/Docker Mode" : "how-to/vm-onboarding-getting-started.md"
      - "SystemD Based Non-BTF Environments": "how-to/systemd-nonbtf.md"
    - "Create Tokens" : "how-to/how-to-create-tokens.md"
    - "Create Labels" : "how-to/how-to-create-labels.md"
    - "Signup/Login via SSO": "how-to/sso.md"
    - "Generate CWPP Reports": "how-to/cwpp-reports-generation.md"
    - "Perform Github IaC Scan": "how-to/github-iac-scan.md"
    - "Onboard Private Github Repositories" : "how-to/private-github-repo-onboarding.md"
    - "Automated Ticket Creation Using Rules Engine": "how-to/rules-engine-ticket-creation.md"
  - "Integrations":
    - "CI/CD":
        - "Azure DevOps":
          - "DAST": "integrations/azure-dast.md"
          - "SAST": "integrations/azure-sast.md"
          - "Container Image Scan": "integrations/azure-container-scan.md"
          - "Iac Scan": "integrations/azure-iac.md"
        - "Google Cloud Build":
          - "Container Image Scan": "integrations/google-build.md"
          - "IaC Scan": "integrations/google-iac.md"
          - "DAST": "integrations/google-dast.md"
          - "SAST": "integrations/google-sast.md"
        - "Harness":
          - "Container Image Scan": "integrations/harness-container-scan.md"
          - "IaC Scan": "integrations/harness-iac-scan.md"
        - "Jenkins":
          - "Container Scan": "integrations/jenkins-container-scan.md"
          - "IaC Scan": "integrations/jenkins-iac-scan.md"
          - "DAST": "integrations/jenkins-dast.md"
          - "SAST": "integrations/jenkins-sast.md"
        - "AWS Code Pipeline":
          - "Container Scan": "integrations/aws-container-scan.md"
          - "IaC Scan": "integrations/aws-iac-scan.md"
          - "DAST": "integrations/aws-dast.md"
          - "SAST": "integrations/aws-sast.md"
        - "Gitlab":
            - "Container Scan": "integrations/gitlab-container-scan.md"
            - "IaC Scan (AccuKnox)": "integrations/gitlab-iac-scan.md"
            - "IaC Scan (GitLab Pipeline)": "integrations/gitlab-pipeline-iac-scan.md"
            - "DAST": "integrations/gitlab-dast.md"
            - "SAST": "integrations/gitlab-sast.md"
        - "CheckMarx":
            - "SAST": "integrations/checkmarx-sast.md"
    - "Container Platform":
        - "Nutanix":
          - "AccuKnox": "integrations/nutanix-accuknox.md"
          - "KubeArmor": "integrations/nutanix-kubearmor.md"
        - "Mirantis Lens" :
          - "KubeArmor": "integrations/lens-ka.md"
          - "AccuKnox Agents": "integrations/lens-ak.md"
        - "Rafay": "integrations/rafay-accuknox.md"
    - "Marketplace":
        - "AWS Marketplace" :
          - "AWS Installation Guide": "integrations/aws-playbook.md"
          - "KubeArmor Installation Guide": "integrations/aws-kubearmor.md"
          - "KubeArmor EKS add-on": "integrations/ka-eks-add-on.md"
        - "Azure Marketplace Installation Guide": "integrations/azure-playbook.md"
        - "Oracle Marketplace Installation Guide": "integrations/oracle-playbook.md"
        - "RedHat Marketplace Installation Guide": "integrations/rh-playbook.md"
    - "Notification":
        - "Slack": "integrations/slack.md"
        - "Email": "integrations/email.md"
        - "Email Backend" : "integrations/email-backend.md"
    - "OAuth": "integrations/oauth.md"
    - "SIEM/ Security Events" :
        - "Telemetry (Sample)" :
          - "Logs" : "integrations/telemetry-logs.md"
          - "Alerts" : "integrations/telemetry-alerts.md"
        - "Splunk" : "integrations/splunk.md"
        - "AWS Cloudwatch" : "integrations/aws-cloudwatch.md"
        - "Rsyslog" : "integrations/rsyslog.md"
        - "Azure Sentinel" : "integrations/azure-sentinel.md"
        - "Forwarding events to AccuKnox SplunkApp" : "integrations/accuKnox-splunk-app-installation-configuration.md"
        - "Rsyslog feeder integration" : "integrations/rsyslog_feeder_integration.md"
        - "Azure Sentinel feeder integration" : "integrations/azure-sentinel-feeder-integration.md"
        - "KubeArmor Splunk Integration" : "integrations/splunk_feeder_kubearmor.md"
    - "Ticketing" :
        - "Jira cloud" : "integrations/jira-cloud.md"
        - "Jira Server" : "integrations/jira-server-cspm.md"
        - "Freshservice" : "integrations/freshservice-cspm.md"
        - "Connectwise" : "integrations/connectwise-cspm.md"
        - "ServiceNow" : "integrations/servicenow.md"
  - "Use-Cases":
    - "CNAPP Security Overview": "use-cases/cnapp-security-overview.md"
    - "DevSecOps (ASPM)":
      - "IaC Scan AWS S3 Buckets (CI/CD Pipeline)": "use-cases/iac-scan.md"
      - " ASPM Container Scan": "use-cases/container-scan.md"
      - "SAST - SQL Injection": "use-cases/sast-sq.md"
    - "Vulnerability Management (ASPM)" : "use-cases/vulnerability.md"
    - "Cloud Security (CSPM)":
      - "Asset Inventory": "use-cases/asset-inventory.md"
      - "Cloud Misconfiguration and Drift Detection" : "use-cases/cloud-misconfigurations.md"
    - "Container Security (CWPP)":
      - "Container Image Scan": "use-cases/image-scan.md"
      - "Runtime Application Hardening" : "use-cases/app-hardening.md"
      - "Workload Hardening": "use-cases/hardening.md"
      - "Network Micro-segmentation" : "use-cases/network-segmentation.md"
      - "Cluster Misconfiguration Scan" : "use-cases/cluster-misconfiguration-scanning.md"
      - "Pod Security Admission Control" : "use-cases/pod-security-admission-controller.md"
      - "Admission Controller": "use-cases/admission-controller-knoxguard.md"
    - "Least Permissive Posture Assessment (CWPP)":
      - "Runtime Application Behavior Discovery": "use-cases/app-behavior.md"
      - "Audit/Forensics": "use-cases/forensics.md"
      - "Zero Trust Security": "use-cases/zero-trust.md"
    - "AI Workload Security (CWPP)":
      - "Jupyter Notebook": "use-cases/jupyter-notebook.md"
    - "Advanced Persistent Threat (CWPP)":
      - "Cryptojacking" : "use-cases/crypto-mining.md"
      - "Hildegard" : "use-cases/hildegard.md"
    - "Securing Secrets Managers (CWPP)" :
      - "HashiCorp Vault Hardening" : "use-cases/hashicorp.md"
      - "CyberArk Conjur Hardening" : "use-cases/cyberark-conjur.md"
    - "Host Security (CWPP)":
      - "Host Scan": "use-cases/host-sec.md"
      - "Malware Scan": "use-cases/malware-scan.md"
      - "VM Hardening": "use-cases/vm-hardening.md"
    - "Kubernetes Identity and Entitlement Management (KIEM)" : "use-cases/kiem.md"
    - "Continuous Compliance (GRC)":
      - "Multi-cloud Compliance": "use-cases/compliance.md"
    - "5G Control Plane Security" : "use-cases/5g-security.md"
    - "IoT/Edge Security" : "use-cases/iot-edge-security.md"

  - "Support Matrix":
    - "KubeArmor Support Matrix" : "support-matrix/kubearmor-support-matrix.md"
    - "Public Cloud" : "support-matrix/public-cloud.md"
    - "Private Cloud" : "support-matrix/private-cloud.md"
    - "VMs" : "support-matrix/vms.md"
    - "Compliance Matrix" : "support-matrix/compliance-matrix.md"
    - "CSPM Assets Support" : "support-matrix/assets-list.md"
    - "Container Registry" : "support-matrix/registry.md"

  - "Resources":
    - "Calculate Pricing":
      - "CSPM Cloud Assets": "resources/count-assets.md"
      - "CWPP Container Images": "resources/count-registry.md"
      - "CWPP Worker Nodes": "resources/count-nodes.md"
    - "Upgrading AccuKnox Agents": "resources/upgrade-ak-agents.md"
    - "Backup my Scan Data": "resources/scan-data-backup.md"
    - "Troubleshooting": "resources/troubleshooting.md"
    - "User Manual": "resources/accuknox-manual.md"
    - "Technical Support Guide": "resources/technical-support-guide.md"
    - "Ticketing Procedures": "resources/ticket-procedure.md"
    - "Glossary": "resources/glossary.md"

  - "FAQs": "faqs.md"