# Project information
site_name: ""
site_description: "Zero trust Runtime Kubernetes security"
site_author: "Ravi Kishor"
site_url: "https://accuknox.com/"
# Copyright
copyright: "&copy; 2023 AccuKnox. All Rights Reserved."
# Repository
repo_name: "GitHub"
repo_url: "https://github.com/kubearmor/KubeArmor"
edit_uri: "https://github.com/accuknox/help-test/edit/main/docs"
# Configuration
docs_dir: "docs"
dev_addr: '127.0.0.1:80'
theme:
  name: "material"
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: white
      #accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'assets/images/logo-black.png'
  logo_dark_mode: 'assets/images/logo-white.png'
  logo_light_mode: 'assets/images/logo-black.png'
  favicon: 'assets/images/favicon.ico'
  hide:
  - toc

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - external-markdown
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - redirects:
        redirect_maps:
            'index.md': 'introduction/accuknox-architecture.md'
# Customization
#extra_javascript:
# - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
- "assets/stylesheets/style.css"
- "assets/stylesheets/extra.css"
extra:
  analytics:
    provider: google
    property: G-QP9CWLWH0P
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/accuknox"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/AccuKnox"
    - icon: "fontawesome/brands/slack"
      link: "https://kubearmor.slack.com/join/shared_invite/zt-1ltmqdbc6-rSHw~LM6MesZZasmP2hAcA#/shared-invite/email"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/accuknox/?original_referer=https%3A%2F%2Fwww.accuknox.com%2F"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCLqK0vGQTa2ctjnbNzvP52Q"
# Page tree
pages:


nav:
  - "Introduction":
    - "Accuknox Architecture" : "introduction/accuknox-architecture.md"
    - "Open source vs Enterprise" : "introduction/open-source-vs-enterprise.md"

  - "Enterprise SaaS":
    - "Dashboard" : "saas/dashboard.md"
    - "Inventory" : 
          - "Assets": "saas/assets.md"
          - "Cloud Workloads" : "saas/cloud-workloads.md"
          - "Imports" : "saas/imports.md"
          - "Explorer" : "saas/explorer.md"
          - "Baselines" : "saas/inventory-baseline.md"
    - "Issues" :
          - "Vulnerabilities" : "saas/vulnerabilities.md"
          - "Registry Scan" : "saas/registry-scan.md"
          - "Risk-based Prioritization" : "saas/risk-based-prioritization.md"
    - "Compliance" : 
          - "Baselines" : "saas/baselines.md"
          - "CSPM Executive Dashboard" : "saas/cspm-executive-dashboard.md"
    - "Runtime Protection" : 
          - "CWPP Dashboard" : "saas/cwpp-dashboard.md"
          - "App Behavior" : "saas/app-behavior.md"
          - "Policies" : "saas/policies.md"
    - "Remediation" : 
          - "Ticket Summary" : "saas/ticket-summary.md"
    - "Monitors/Logging" : 
          - "Logs" : "saas/logs.md"
          - "Triggers" : "saas/triggers.md"
          - "Monitors" : "saas/monitors.md"
    - "Reports" : "saas/reports.md"
    - "Notification" : 
         - "Slack" : "saas/slack.md"
         - "Email" : "saas/email.md" 
    - "Settings" : 
          - "Cloud Accounts" : "saas/cloud-accounts.md"
          - "Manage Cluster" : "saas/manage-cluster.md"
          - "User Management" : "saas/user-management.md"
          - "RBAC" : "saas/rbac.md"
          - "Integrations" : "saas/integrations.md"
          - "Labels" : "saas/labels.md"
          - "Tags" : "saas/tags.md"
          - "Groups" : "saas/groups.md"
          - "Ticket Template" : "saas/ticket-template.md"

  - "Getting Started":
    - "Open Source Installation": "getting-started/open-source.md"
    - "Enterprise SaaS Installation" : 
        - "Prerequisites" :
          - "CSPM Prerequisites":
            - "AWS": "getting-started/cspm-prereq-aws.md"
            - "Azure": "getting-started/cspm-prereq-azure.md"
            - "GCP": "getting-started/cspm-prereq-gcp.md"
          - "CWPP Prerequisites": "getting-started/cwpp-prereq.md"
        - "Onboarding" :
          - "Cloud Account" :
            - "AWS" : "getting-started/aws-onboarding.md"
            - "Azure" : "getting-started/azure-onboarding.md"
            - "GCP" : "getting-started/gcp-onboarding.md"
          - "Cluster" :
            - "Unmanaged" : "getting-started/cluster-onboarding-unmanaged.md"
            - "Managed" : "getting-started/cluster-onboarding-managed.md"
            - "Cluster Offboarding" : "getting-started/cluster-offboarding.md"
        - "5G Security Prerequisites": "getting-started/5gsec-prereq.md"
        - "IoT/Edge Prerequisites": "getting-started/iot-edge-prereq.md"
    - "On-prem Installation" :
        - "On-prem Prerequisites" : "getting-started/on-prem-prereq.md"
        - "On-prem Installation Guide" : "getting-started/on-prem-installation-guide.md"
    - "AccuKnox Agents" : "getting-started/accuknox-agents.md"
    - "Release Notes":
        - "AccuKnox" : "getting-started/accuknox-release.md"
        - "KubeArmor" : "getting-started/kubearmor-release.md"
    - "Support Matrix":
        - "KubeArmor Support Matrix" : "getting-started/kubearmor-support-matrix.md"
        - "Public Cloud" : "getting-started/public-cloud.md"
        - "Private Cloud" : "getting-started/private-cloud.md"
        - "VMs" : "getting-started/vms.md"
        - "Supported Benchmarks" : "getting-started/supported-benchmarks.md"
        - "Assets list" : "getting-started/assets-list.md" 
    - "Sample Workloads Protection" :
      - "WordPress-MySQL Protection": "getting-started/wordpress-mysql.md" 
      - "DVWA Protection": "getting-started/dvwa.md"  
      - "PHP-MySQL Protection": "getting-started/php-mysql.md"

  - "Integrations":
    - "SIEM/ Security Events" : 
        - "Telemetry (Sample)" : 
          - "Logs" : "integrations/telemetry-logs.md"
          - "Alerts" : "integrations/telemetry-alerts.md"
        - "Splunk" : "integrations/splunk.md"
        - "AWS Cloudwatch" : "integrations/aws-cloudwatch.md"
        - "Rsyslog" : "integrations/rsyslog.md"
        - "Azure Sentinel" : "integrations/azure-sentinel.md"
        - "Forwarding events to AccuKnox SplunkApp" : "integrations/accuKnox-splunk-app-installation-configuration.md"
        - "Rsyslog feeder integration" : "integrations/rsyslog_feeder_integration.md"
        - "Azure Sentinel feeder integration" : "integrations/azure-sentinel-feeder-integration.md" 
        - "KubeArmor Splunk Integration" : "integrations/splunk_feeder_kubearmor.md"
    - "Registry": "integrations/registry.md"
    - "Ticketing" :
        - "Jira cloud" : "integrations/jira-cloud-cwpp.md"
        - "Jira Server" : "integrations/jira-server-cspm.md"
        - "Freshservice" : "integrations/freshservice-cspm.md"
        - "Connectwise" : "integrations/connectwise-cspm.md"
    - "Notification":
        - "Slack": "integrations/slack.md"
    - "Marketplace Listing":
        - "AWS Marketplace" :
          - "KubeArmor Installation Steps": "integrations/aws-kubearmor.md"
          - "User Playbook": "integrations/aws-playbook.md"
    - "Platform":
        - "Rafay": "integrations/rafay-accuknox.md"

  - "Use-Cases":
    - "Securing the Secrets Manager" :
      - "HashiCorp Vault Hardening" : "use-cases/hashicorp.md"
      - "CyberArk Conjur Hardening" : "use-cases/cyberark-conjur.md"
    - "CSPM":
      - "Vulnerability Management" : "use-cases/vulnerability.md"
      - "Cloud Misconfiguration and Drift Detection" : "use-cases/cloud-misconfigurations.md"
      - "Container Security" :
        - "Image Scan": "use-cases/image-scan.md" 
      - "Asset Inventory" : "use-cases/asset-inventory.md"
    - "CWPP":
      - "Runtime Application Behavior": "use-cases/app-behavior.md"
      - "Runtime Application Hardening" : "use-cases/app-hardening.md"
      - "Network Micro-segmentation" : "use-cases/network-segmentation.md"
    - "5G Control Plane Security" : "use-cases/5g-security.md"
    - "IoT/Edge Security" : "use-cases/iot-edge-security.md"

  - "Resources":
    - "Calculate Pricing":
      - "Count my Cloud Assets": "resources/count-assets.md"
      - "Count my Container Registries": "resources/count-registry.md"
      - "Count my K8s Cluster Worker Nodes": "resources/count-nodes.md"
    - "Backup my Scan Data": "resources/scan-data-backup.md"
    - "Troubleshooting": "resources/troubleshooting.md"
    - "User Manual": "resources/accuknox-manual.md"
    
  - "FAQs":
    - "" : "faqs/troubleshooting-and-faqs.md"

