# Project information
site_name: ""
site_description: "Zero trust CNAPP"
site_author: "AccuKnox"
site_url: "https://help.accuknox.com/"
# Copyright
copyright: "&copy; 2024 AccuKnox. All Rights Reserved."
# Repository
repo_name: "GitHub"
repo_url: "https://github.com/kubearmor/KubeArmor"
edit_uri: "https://github.com/accuknox/help-test/edit/main/docs"
# Configuration
docs_dir: "docs"
dev_addr: '127.0.0.1:8000'
theme:
  name: "material"
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: white
      #accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  font:
    text: 'Montessarat'
    code: 'Montessarat'
  #icon:
  #logo: 'assets/images/logo-black.png'
  logo_dark_mode: 'assets/images/logo-white.png'
  logo_light_mode: 'assets/images/logo-black.png'
  favicon: 'assets/images/favicon.ico'
  hide:
  - toc

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - neoteroi.cards
plugins:
  - external-markdown
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - redirects:
        redirect_maps:
            'index.md': 'introduction/accuknox-architecture.md'
# Customization
#extra_javascript:
# - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
- "assets/stylesheets/style.css"
- "assets/stylesheets/extra.css"
- "assets/stylesheets/neoteroi-mkdocs.css"
extra:
  analytics:
    provider: google
    property: G-QP9CWLWH0P
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/accuknox"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/AccuKnox"
    - icon: "fontawesome/brands/slack"
      link: "https://kubearmor.slack.com/join/shared_invite/zt-1ltmqdbc6-rSHw~LM6MesZZasmP2hAcA#/shared-invite/email"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/accuknox/?original_referer=https%3A%2F%2Fwww.accuknox.com%2F"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCLqK0vGQTa2ctjnbNzvP52Q"
# Page tree
pages:


nav:
  - "Introduction":
    - "Accuknox Architecture" : "introduction/accuknox-architecture.md"
    - "Open source vs Enterprise" : "introduction/open-source-vs-enterprise.md"

  # - "Enterprise SaaS":
  #   - "Dashboard" : "saas/dashboard.md"
  #   - "Inventory" : 
  #         - "Assets": "saas/assets.md"
  #         - "Cloud Workloads" : "saas/cloud-workloads.md"
  #        # - "Imports" : "saas/imports.md"
  #        # - "Explorer" : "saas/explorer.md"
  #        # - "Baselines" : "saas/inventory-baseline.md"
  #   - "Issues" :
  #         - "Vulnerabilities" : "saas/vulnerabilities.md"
  #         - "Registry Scan" : "saas/registry-scan.md"
  #        # - "Risk-based Prioritization" : "saas/risk-based-prioritization.md"
  #   - "Compliance" : 
  #        # - "Baselines" : "saas/baselines.md"
  #         - "CSPM Executive Dashboard" : "saas/cspm-executive-dashboard.md"
  #   - "Runtime Protection" : 
  #         - "CWPP Dashboard" : "saas/cwpp-dashboard.md"
  #         - "App Behavior" : "saas/app-behavior.md"
  #         - "Policies" : "saas/policies.md"
  #   - "Remediation" : 
  #         - "Ticket Summary" : "saas/ticket-summary.md"
  #   - "Monitors/Logging" : 
  #         - "Logs" : "saas/logs.md"
  #         - "Triggers" : "saas/triggers.md"
  #       #  - "Monitors" : "saas/monitors.md"
  #   - "Reports" : "saas/reports.md"
  #   - "Notification" : 
  #        - "Slack" : "saas/slack.md"
  #        - "Email" : "saas/email.md" 
  #   - "Settings" : 
  #         - "Cloud Accounts" : "saas/cloud-accounts.md"
  #         - "Manage Cluster" : "saas/manage-cluster.md"
  #         - "User Management" : "saas/user-management.md"
  #         - "RBAC" : "saas/rbac.md"
  #         - "Integrations" : "saas/integrations.md"
  #         - "Labels" : "saas/labels.md"
  #         - "Tags" : "saas/tags.md"
  #         - "Groups" : "saas/groups.md"
  #         - "Ticket Template" : "saas/ticket-template.md"

  - "Getting Started":
    - "Open Source Installation": "getting-started/open-source.md"
    - "Deployment Models" :
      - "SaaS" : 
          - "Prerequisites" :
            - "CSPM Prerequisites":
              - "AWS": "getting-started/cspm-prereq-aws.md"
              - "Azure": "getting-started/cspm-prereq-azure.md"
              - "GCP": "getting-started/cspm-prereq-gcp.md"
            - "CWPP Prerequisites": "getting-started/cwpp-prereq.md"
          - "Onboarding" :
            - "Cloud Account" :
              - "AWS" : "getting-started/aws-onboarding.md"
              - "Azure" : "getting-started/azure-onboarding.md"
              - "GCP" : "getting-started/gcp-onboarding.md"
            - "Cluster" :
              - "Unmanaged" : "getting-started/cluster-onboarding-unmanaged.md"
              - "Managed" : "getting-started/cluster-onboarding-managed.md"
              - "Cluster Offboarding" : "getting-started/cluster-offboarding.md"
            - "Registry":
              - "ACR": "getting-started/acr.md"
              - "ECR": "getting-started/ecr.md"
              - "GAR": "getting-started/gar.md"
            - "VM" : "getting-started/vm-onboarding.md"
      - "On-prem Installation" : "getting-started/on-prem-installation-guide.md"
      - "DevSecOps" : "getting-started/devsecops.md"
    - "AccuKnox Agents" : "getting-started/accuknox-agents.md"
    - "Release Notes":
        - "AccuKnox" : 
           - "V1.7 Release Notes" : "getting-started/1-7-release.md"
           - "v1.6 Release Notes" : "getting-started/1-6-release.md"
           - "v1.5 Release Notes" : "getting-started/1-5-release.md"
        - "KubeArmor" : "getting-started/kubearmor-release.md"
    - "Sample Workloads Protection" :
      - "WordPress-MySQL Protection": "getting-started/wordpress-mysql.md" 
      - "DVWA Protection": "getting-started/dvwa.md"  
      - "PHP-MySQL Protection": "getting-started/php-mysql.md"

  - "Integrations":
    - "SIEM/ Security Events" : 
        - "Telemetry (Sample)" : 
          - "Logs" : "integrations/telemetry-logs.md"
          - "Alerts" : "integrations/telemetry-alerts.md"
        - "Splunk" : "integrations/splunk.md"
        - "AWS Cloudwatch" : "integrations/aws-cloudwatch.md"
        - "Rsyslog" : "integrations/rsyslog.md"
        - "Azure Sentinel" : "integrations/azure-sentinel.md"
        - "Forwarding events to AccuKnox SplunkApp" : "integrations/accuKnox-splunk-app-installation-configuration.md"
        - "Rsyslog feeder integration" : "integrations/rsyslog_feeder_integration.md"
        - "Azure Sentinel feeder integration" : "integrations/azure-sentinel-feeder-integration.md" 
        - "KubeArmor Splunk Integration" : "integrations/splunk_feeder_kubearmor.md"
    - "Ticketing" :
        - "Jira cloud" : "integrations/jira-cloud-cwpp.md"
        - "Jira Server" : "integrations/jira-server-cspm.md"
        - "Freshservice" : "integrations/freshservice-cspm.md"
        - "Connectwise" : "integrations/connectwise-cspm.md"
        - "ServiceNow" : "integrations/servicenow.md"
    - "Notification":
        - "Slack": "integrations/slack.md"
        - "Email": "integrations/email.md"
        - "Email Backend" : "integrations/email-backend.md"
    - "Marketplace Listing":
        - "AWS Marketplace" :
          - "AccuKnox User Playbook": "integrations/aws-playbook.md"
          - "KubeArmor User Playbook": "integrations/aws-kubearmor.md"
          - "KubeArmor - Amazon EKS add-on": "integrations/ka-eks-add-on.md"
    - "Platform":
        - "D2iQ": "integrations/d2iq.md"
        - "Lens" :
          - "KubeArmor": "integrations/lens-ka.md"
          - "AccuKnox Agents": "integrations/lens-ak.md"
        - "OAuth": "integrations/oauth.md"
        - "Rafay": "integrations/rafay-accuknox.md"

  - "Use-Cases":
    - "Cloud Security (CSPM)":
      - "Asset Inventory": "use-cases/asset-inventory.md"
      - "Cloud Misconfiguration and Drift Detection" : "use-cases/cloud-misconfigurations.md"
    - "Container Security (CWPP)":
      - "Container Image Scan": "use-cases/image-scan.md"
      - "Runtime Application Hardening" : "use-cases/app-hardening.md"
      - "Workload Hardening": "use-cases/hardening.md"
      - "Network Micro-segmentation" : "use-cases/network-segmentation.md"
    - "Least Permissive Posture Assessment (CWPP)":
      - "Runtime Application Behavior Discovery": "use-cases/app-behavior.md"
      - "Audit/Forensics": "use-cases/forensics.md"
      - "Zero Trust Security": "use-cases/zero-trust.md"
    - "AI Workload Security (CWPP)":
      - "Jupyter Notebook": "use-cases/jupyter-notebook.md"
    - "Advanced Persistent Threat (CWPP)":
      - "Cryptojacking" : "use-cases/crypto-mining.md"
      - "Hildegard" : "use-cases/hildegard.md"
    - "Securing Secrets Managers (CWPP)" :
      - "HashiCorp Vault Hardening" : "use-cases/hashicorp.md"
      - "CyberArk Conjur Hardening" : "use-cases/cyberark-conjur.md"
    - "DevSecOps (ASPM)":
      - "IaC Scan": "use-cases/iac-scan.md"
      - "Container Scan": "use-cases/container-scan.md"
    - "Continuous Compliance (GRC)":
      - "Multi-cloud Compliance": "use-cases/compliance.md"
    - "Host Security (CWPP)": 
      - "Host Scan": "use-cases/host-sec.md"
      - "Malware Scan": "use-cases/malware-scan.md"
    - "Vulnerability Management (ASPM)" : "use-cases/vulnerability.md"
    - "5G Control Plane Security" : "use-cases/5g-security.md"
    - "IoT/Edge Security" : "use-cases/iot-edge-security.md"
    
  - "Support Matrix":
    - "KubeArmor Support Matrix" : "support-matrix/kubearmor-support-matrix.md"
    - "Public Cloud" : "support-matrix/public-cloud.md"
    - "Private Cloud" : "support-matrix/private-cloud.md"
    - "VMs" : "support-matrix/vms.md"
    - "Supported Benchmarks" : "support-matrix/supported-benchmarks.md"
    - "CSPM Assets Support" : "support-matrix/assets-list.md"

  - "Resources":
    - "Calculate Pricing":
      - "Count my Cloud Assets": "resources/count-assets.md"
      - "Count my Container Registries": "resources/count-registry.md"
      - "Count my K8s Cluster Worker Nodes": "resources/count-nodes.md"
    - "Upgrading AccuKnox Agents": "resources/upgrade-ak-agents.md"
    - "Backup my Scan Data": "resources/scan-data-backup.md"
    - "Troubleshooting": "resources/troubleshooting.md"
    - "User Manual": "resources/accuknox-manual.md"
    - "Technical Support Guide": "resources/technical-support-guide.md"
    - "Ticketing Procedures": "resources/ticket-procedure.md"
    - "Glossary": "resources/glossary.md"
    
  - "FAQs": "faqs.md"

