apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-discovery-process-discovery
  namespace: wordpress-mysql
spec:
  tags: ["MITRE", "Discovery"]
  message: "Someone accessed running process"
  selector:
    matchLabels:
      app: wordpress
  process:
    matchPaths:
      - path: /bin/ps
      - path: /usr/bin/ps
      - path: /usr/bin/pgrep
      - path: /usr/bin/top
      - path: /usr/bin/htop
    action: Audit
    severity: 5
