apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-nist-ca-9-audit-untrusted-read-on-sensitive-files
spec:
  tags: ["NIST","NIST-800-53-r5","CA-9","File Rules","Internal System Connections", "NIST_SA", "NIST_SA-20", "NIST_SA-20-Customized Development of Critical Components", "SA"]
  message: "Alert! Sensitive file opened for reading by non-trusted program! Possible violation of NIST CA-9 SA-20"
  nodeSelector:
    matchLabels:
     kubernetes.io/hostname: gke-ubuntu                                                                           # Change your matchLabels
  file:
    severity: 5
    matchDirectories:
    - dir: /etc/sudoers.d/
      ownerOnly: true
      recursive: true
    - dir: /etc/pam.d/ 
      ownerOnly: true
      recursive: true
    - dir: /etc/
      ownerOnly: true
      recursive: true
    action: Audit
    matchPaths:
    - path: /etc/shadow
      ownerOnly: true
    - path: /etc/sudoers
      ownerOnly: true
    - path: /etc/pam.conf
      ownerOnly: true
    - path: /etc/security/pwquality.conf
      ownerOnly: true
    action: Audit
