"""Import a Salesforce export (Account, Contact, Opportunity CSVs) into the CRM REST API.

Scope "pipeline": every opportunity, the accounts those opportunities belong to, and
the contacts at those accounts. Scope "all": every row in the three files.

The run is resumable. state.json maps each Salesforce Id to the CRM id it produced,
so a rerun skips finished work. Every failure goes to errors.csv with the reason.

Environment:
    CRM_API_KEY               the CRM key (never commit it)
    CRM_DEFAULT_OWNER_EMAIL   the CRM user who owns deals with no matching owner
    CRM_IMPORT_DIR            the folder with the three CSVs (default: current folder)

Usage:
    python salesforce_import.py --dry-run    # map everything, write nothing
    python salesforce_import.py --limit 5    # pilot: 5 opportunities and their records
    python salesforce_import.py              # full run in the chosen scope
"""

import argparse
import csv
import json
import os
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests

API = "https://crm.accuknox.com/rest"
KEY = os.environ.get("CRM_API_KEY", "")
# Folder that holds Account.csv, contact.csv and Opportunties.csv.
DOWNLOADS = os.environ.get("CRM_IMPORT_DIR", os.getcwd())
HERE = os.path.dirname(os.path.abspath(__file__))
STATE_PATH = os.path.join(HERE, "state.json")
ERRORS_PATH = os.path.join(HERE, "errors.csv")

# Deals whose Salesforce owner has no CRM account go to this CRM user.
DEFAULT_OWNER_EMAIL = os.environ.get("CRM_DEFAULT_OWNER_EMAIL", "")
WORKERS = 8

# Websites that name a hosting or social site, never the company itself.
JUNK_DOMAINS = {
    "linkedin.com", "linktr.ee", "facebook.com", "twitter.com", "x.com",
    "instagram.com", "youtube.com", "github.com", "google.com", "sites.google.com",
    "gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "bit.ly", "wixsite.com",
    "wordpress.com", "blogspot.com", "medium.com", "crunchbase.com", "zoominfo.com",
    "meetup.com", "angel.co", "wellfound.com",
}

# Salesforce opportunity stage -> CRM DealStage. The original stage is kept in a field.
STAGE_MAP = {
    "Event Lead": "DEMO_BOOKED",
    "Presentation/ Demo": "DEMO_BOOKED",
    "Follow Up": "QUALIFIED_TO_BUY",
    "POC WIP": "DECISION_MAKER_BOUGHT_IN",
    "POC Complete": "DECISION_MAKER_BOUGHT_IN",
    "Price Quote Submitted": "CONTRACT_SENT",
    "Closed Won": "CLOSED_WON",
    "Closed Lost": "CLOSED_LOST",
    "Customer Churn": "CLOSED_LOST",
    "Archived": "CLOSED_LOST",
}

# Customer_Partner_Location__c -> the existing "Territory" select field.
TERRITORY_MAP = {
    "india": "APAC", "apac": "APAC", "asia": "APAC", "north america": "AMER",
    "south america": "AMER", "latam": "AMER", "europe": "EMEA", "africa": "EMEA",
    "middle east": "EMEA",
}

# The server's own email check (zod z.email()). A looser check lets masked
# addresses like "kp.@example.com" through and the create fails with 400.
EMAIL_RE = re.compile(r"^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$")

# Custom fields this import creates, per entity. agentFilled is False so the
# agent never overwrites Salesforce history.
FIELD_SPECS = {
    "COMPANY": [
        ("sf_id", "Salesforce ID", "TEXT"),
        ("sf_account_stage", "SF account stage", "TEXT"),
        ("sf_account_status", "SF account status", "TEXT"),
        ("sf_type", "SF account type", "TEXT"),
        ("employees", "Employees", "NUMBER"),
        ("annual_revenue", "Annual revenue", "NUMBER"),
        ("prospect_interest", "Prospect interest", "TEXT"),
        ("competition", "Competition", "TEXT"),
        ("partner_type", "Partner type", "TEXT"),
        ("sf_owner", "Salesforce owner", "TEXT"),
        ("sf_source", "Salesforce source", "TEXT"),
        ("sf_notes", "Salesforce notes", "LONG_TEXT"),
    ],
    "CONTACT": [
        ("sf_id", "Salesforce ID", "TEXT"),
        ("department", "Department", "TEXT"),
        ("management_level", "Management level", "TEXT"),
        ("mobile", "Mobile", "PHONE"),
        ("country", "Country", "TEXT"),
        ("city", "City", "TEXT"),
        ("sf_source", "Salesforce source", "TEXT"),
    ],
    "DEAL": [
        ("sf_id", "Salesforce ID", "TEXT"),
        ("sf_stage", "SF stage", "TEXT"),
        ("sf_owner", "Salesforce owner", "TEXT"),
        ("requirement", "Requirement", "TEXT"),
        ("prospect_interest", "Prospect interest", "TEXT"),
        ("competition", "Competition", "TEXT"),
        ("solution_engineer", "Solution engineer", "TEXT"),
        ("lead_generated_by", "Lead generated by", "TEXT"),
        ("potential", "Potential", "TEXT"),
        ("bant_score", "BANT score", "TEXT"),
        ("mrr", "MRR", "NUMBER"),
        ("arr", "ARR", "NUMBER"),
        ("first_demo_date", "First demo date", "DATE"),
        ("sf_created", "Salesforce created date", "DATE"),
    ],
}


# ---------------------------------------------------------------- helpers

def clean(value):
    value = (value or "").strip()
    return "" if value.lower() in {"na", "n/a", "none", "null", "-"} else value


def domain_of(website):
    w = clean(website).lower()
    if not w:
        return None
    w = re.sub(r"^[a-z][a-z0-9+.-]*://", "", w)
    host = re.split(r"[/?#:\s]", w, maxsplit=1)[0]
    host = host[4:] if host.startswith("www.") else host
    if not re.fullmatch(r"[a-z0-9-]+(\.[a-z0-9-]+)+", host):
        return None
    if host in JUNK_DOMAINS or any(host.endswith("." + j) for j in JUNK_DOMAINS):
        return None
    return host


def number(value):
    try:
        n = float(clean(value).replace(",", ""))
        return n if n == n else None
    except ValueError:
        return None


def iso_date(value):
    v = clean(value)
    return v[:10] if re.match(r"^\d{4}-\d{2}-\d{2}", v) else None


def joined(*parts, sep="\n\n"):
    return sep.join(p for p in (clean(x) for x in parts) if p)


def linkedin(value):
    v = clean(value)
    if not v or "linkedin.com" not in v.lower():
        return None
    return v if v.lower().startswith("http") else "https://" + v


def territory(location):
    loc = clean(location).lower()
    for needle, label in TERRITORY_MAP.items():
        if needle in loc:
            return label
    return None


def read_csv(name):
    with open(os.path.join(DOWNLOADS, name), encoding="utf-8-sig", errors="replace") as f:
        return list(csv.DictReader(f))


# ---------------------------------------------------------------- API client

class Api:
    def __init__(self, dry_run):
        self.dry = dry_run
        self.local = threading.local()

    def session(self):
        if not hasattr(self.local, "s"):
            s = requests.Session()
            s.headers.update({"x-api-key": KEY, "content-type": "application/json"})
            self.local.s = s
        return self.local.s

    def call(self, method, path, body=None, params=None):
        for attempt in range(6):
            try:
                r = self.session().request(method, API + path, json=body, params=params, timeout=60)
            except requests.RequestException as exc:
                err = str(exc)
            else:
                if r.status_code < 400:
                    return r.json() if r.content else None
                if r.status_code not in (429, 500, 502, 503, 504):
                    raise ApiError(r.status_code, r.text[:500])
                err = f"{r.status_code} {r.text[:200]}"
            time.sleep(min(30, 2 ** attempt))
        raise ApiError(0, f"gave up after retries: {err}")


class ApiError(Exception):
    def __init__(self, status, text):
        super().__init__(f"{status}: {text}")
        self.status = status
        self.text = text


# ---------------------------------------------------------------- state

class State:
    def __init__(self):
        self.lock = threading.Lock()
        self.data = {"company": {}, "contact": {}, "deal": {}, "patched": {}, "linked": {}}
        if os.path.exists(STATE_PATH):
            with open(STATE_PATH, encoding="utf-8") as f:
                self.data.update(json.load(f))
        self.dirty = 0

    def get(self, kind, key):
        return self.data[kind].get(key)

    def put(self, kind, key, value):
        with self.lock:
            self.data[kind][key] = value
            self.dirty += 1
            if self.dirty >= 25:
                self.save_locked()

    def save_locked(self):
        tmp = STATE_PATH + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(self.data, f)
        os.replace(tmp, STATE_PATH)
        self.dirty = 0

    def save(self):
        with self.lock:
            self.save_locked()


class Errors:
    def __init__(self):
        self.lock = threading.Lock()
        new = not os.path.exists(ERRORS_PATH)
        self.f = open(ERRORS_PATH, "a", newline="", encoding="utf-8")
        self.w = csv.writer(self.f)
        if new:
            self.w.writerow(["time", "entity", "sf_id", "name", "step", "error"])
        self.count = 0

    def log(self, entity, sf_id, name, step, error):
        with self.lock:
            self.w.writerow([time.strftime("%H:%M:%S"), entity, sf_id, name, step, str(error)[:500]])
            self.f.flush()
            self.count += 1


# ---------------------------------------------------------------- importer

class Importer:
    def __init__(self, args):
        self.args = args
        self.api = Api(args.dry_run)
        self.state = State()
        self.errors = Errors()
        self.stats = {}
        self.stats_lock = threading.Lock()
        # Serialises creates that share a dedupe key, so two threads never
        # create the same company or contact twice.
        self.key_locks = {}
        self.key_locks_lock = threading.Lock()

    def bump(self, name, n=1):
        with self.stats_lock:
            self.stats[name] = self.stats.get(name, 0) + n

    def key_lock(self, key):
        with self.key_locks_lock:
            return self.key_locks.setdefault(key, threading.Lock())

    # ---- setup

    def load(self):
        self.accounts = {a["Id"]: a for a in read_csv("Account.csv")}
        self.contacts = read_csv("contact.csv")
        self.opps = read_csv("Opportunties.csv")

        if self.args.limit:
            self.opps = [o for o in self.opps if o["AccountId"]][: self.args.limit] + \
                        [o for o in self.opps if not o["AccountId"]][: max(1, self.args.limit // 5)]

        if self.args.scope == "all":
            account_ids = set(self.accounts)
        else:
            account_ids = {o["AccountId"] for o in self.opps if o["AccountId"] in self.accounts}
        self.account_ids = account_ids
        # Scope "all" also takes contacts with no Salesforce account. The CRM
        # files them by email domain.
        self.contacts = [c for c in self.contacts if c["AccountId"] in account_ids
                         or (self.args.scope == "all" and not c["AccountId"])]
        if self.args.limit:
            self.contacts = self.contacts[: self.args.limit * 3]
        print(f"scope={self.args.scope}: {len(account_ids)} accounts, "
              f"{len(self.contacts)} contacts, {len(self.opps)} opportunities")

    def load_users(self):
        users = self.api.call("GET", "/users")
        self.users = users
        self.default_owner = next(u["id"] for u in users if u["email"] == DEFAULT_OWNER_EMAIL)

    def owner_for(self, *names):
        """Match a Salesforce owner name to a CRM user by full name, then first name."""
        for raw in names:
            name = clean(raw).lower()
            if not name:
                continue
            for u in self.users:
                un = (u.get("name") or "").lower()
                if un and (un == name or name.split()[0] == un.split()[0]) and un != "website":
                    return u["id"]
        return None

    def ensure_fields(self):
        self.fields = {}
        for entity, specs in FIELD_SPECS.items():
            existing = self.api.call("GET", "/fields", params={"entity": entity, "includeArchived": "true"})
            by_label = {f["label"].lower(): f for f in existing}
            keys = {}
            for short, label, ftype in specs:
                f = by_label.get(label.lower())
                if f is None:
                    if self.args.dry_run:
                        keys[short] = f"<new:{label}>"
                        continue
                    f = self.api.call("POST", "/fields", {
                        "entity": entity, "label": label, "type": ftype,
                        "agentFilled": False, "showOnSheet": True,
                    })
                    self.bump(f"field created ({entity})")
                if f.get("archivedAt"):
                    self.api.call("POST", f"/fields/{f['id']}/restore", {})
                keys[short] = f["key"]
            # Existing select fields this import fills.
            for f in existing:
                if f["key"] in ("territory", "account_type", "lead_source"):
                    keys[f["key"]] = f["key"]
            self.fields[entity] = keys

    def fieldvals(self, entity, values):
        keys = self.fields[entity]
        out = {}
        for short, value in values.items():
            if value in (None, "") or short not in keys:
                continue
            out[keys[short]] = value
        return out

    # ---- existing CRM records, for dedupe against what is already there

    def find_company(self, domain, name):
        if domain:
            rows = self.api.call("POST", "/companies/search", {"q": domain, "pageSize": 20})["rows"]
            for r in rows:
                if (r.get("domain") or "").lower() == domain:
                    return r["id"]
        rows = self.api.call("POST", "/companies/search", {"q": name, "pageSize": 20})["rows"]
        for r in rows:
            if (r.get("name") or "").strip().lower() == name.strip().lower():
                return r["id"]
        return None

    def find_contact(self, email, name=""):
        # Search does not always match a whole address, so also try the local
        # part and the person's name, then compare the email exactly.
        for q in dict.fromkeys([email, email.split("@")[0], name]):
            if not q:
                continue
            for archived in (False, True):
                rows = self.api.call("POST", "/contacts/search",
                                     {"q": q, "pageSize": 100, "archived": archived})["rows"]
                for r in rows:
                    if (r.get("email") or "").lower() == email:
                        return r["id"]
        return None

    # ---- companies

    def company_payloads(self, a):
        name = clean(a["Name"]) or "Unnamed account"
        domain = domain_of(a["Website"])
        owner = self.owner_for(a["Sowner__c"], a["Sales_Owner_Account__c"], a["Sales_Owner__c"])
        country = clean(a["BillingCountry"]) or clean(a["ShippingCountry"])
        city = clean(a["BillingCity"]) or clean(a["ShippingCity"])
        sf_type = clean(a["Type"])
        source = clean(a["Source__c"])
        data = {
            "description": clean(a["Description"]) or clean(a["Company_Description__c"]),
            "industry": clean(a["Industry"]),
            "city": city,
            "country": country,
            "phone": clean(a["Phone"]),
            "linkedinUrl": linkedin(a["Company_LinkedIn__c"]),
        }
        if not domain and clean(a["Website"]):
            data["website"] = clean(a["Website"])
        fields = self.fieldvals("COMPANY", {
            "sf_id": a["Id"],
            "sf_account_stage": clean(a["Account_Stage__c"]),
            "sf_account_status": clean(a["Account_Status__c"]),
            "sf_type": sf_type,
            "employees": number(a["NumberOfEmployees"]),
            "annual_revenue": number(a["Annual_Revenue__c"]),
            "prospect_interest": clean(a["Prospect_Interest__c"]),
            "competition": clean(a["Competition_Tool__c"]),
            "partner_type": clean(a["Partner_Type_Account__c"]),
            "sf_owner": clean(a["Sowner__c"]) or clean(a["Sales_Owner__c"]),
            "sf_source": joined(a["AccountSource"], a["Lead_Generated_via__c"], a["Lead_Gen_Contact_Account__c"], sep=" | "),
            "sf_notes": joined(a["Queries_and_Next_Steps__c"], a["Next_Step_Account__c"], a["High_Value_Notes__c"]),
            "territory": territory(a["Customer_Partner_Location__c"]),
            "account_type": sf_type if sf_type in ("Prospect", "Customer", "Partner") else None,
            "lead_source": source if source in ("Inbound", "Outbound") else None,
        })
        data = {k: v for k, v in data.items() if v}
        if fields:
            data["fields"] = fields
        return {"name": name[:200], "domain": domain, "ownerId": owner}, data

    def import_company(self, sf_id, create, patch):
        """Create (or match) one company, then patch its details. Returns CRM id."""
        crm_id = self.state.get("company", sf_id)
        dedupe = "c:" + (create["domain"] or create["name"].lower())
        if not crm_id:
            with self.key_lock(dedupe):
                crm_id = self.state.get("company", dedupe)
                if not crm_id:
                    crm_id = self.find_company(create["domain"], create["name"])
                    if crm_id:
                        self.bump("company matched existing")
                    else:
                        body = {"name": create["name"]}
                        if create["domain"]:
                            body["domain"] = create["domain"]
                        if create["ownerId"]:
                            body["ownerId"] = create["ownerId"]
                        try:
                            crm_id = self.api.call("POST", "/companies", body)["id"]
                        except ApiError as e:
                            if e.status != 409:
                                raise
                            crm_id = self.find_company(create["domain"], create["name"])
                            if not crm_id:
                                raise
                        self.bump("company created")
                    self.state.put("company", dedupe, crm_id)
                else:
                    self.bump("company merged (same domain/name)")
            self.state.put("company", sf_id, crm_id)
        if patch and not self.state.get("patched", "company:" + crm_id):
            self.patch("company", crm_id, patch)
        return crm_id

    def patch(self, kind, crm_id, data):
        path = {"company": "/companies/", "contact": "/contacts/", "deal": "/deals/"}[kind] + crm_id
        try:
            self.api.call("PATCH", path, {"data": data})
        except ApiError as e:
            # One bad field value must not drop the rest, so retry without fields.
            if e.status == 400 and "fields" in data:
                slim = {k: v for k, v in data.items() if k != "fields"}
                self.errors.log(kind, crm_id, "", "patch fields", e)
                if slim:
                    self.api.call("PATCH", path, {"data": slim})
            else:
                raise
        self.state.put("patched", f"{kind}:{crm_id}", True)
        self.bump(f"{kind} details set")

    # ---- contacts

    def import_contact(self, c):
        sf_id = c["Id"]
        if self.state.get("contact", sf_id) and self.state.get("patched", "contact:" + self.state.get("contact", sf_id)):
            return
        company_id = self.state.get("company", c["AccountId"]) if c["AccountId"] else None
        if c["AccountId"] and not company_id:
            self.errors.log("contact", sf_id, c["Name"], "company", "account was not imported")
            return
        first = clean(c["FirstName"])
        last = clean(c["LastName"])
        if not first:
            first, last = (last or "Unknown"), ""
        email = clean(c["Email"]).lower()
        if email and not EMAIL_RE.match(email):
            email = ""
        if not email:
            personal = clean(c["Personal_Email__c"]).lower()
            email = personal if EMAIL_RE.match(personal) else ""

        crm_id = self.state.get("contact", sf_id)
        if not crm_id:
            dedupe = "p:" + (email or sf_id)
            with self.key_lock(dedupe):
                crm_id = self.state.get("contact", dedupe)
                if not crm_id:
                    body = {"firstName": first[:100], "lastName": last[:100]}
                    if company_id:
                        body["companyId"] = company_id
                    if email:
                        body["email"] = email
                    if clean(c["Title"]):
                        body["title"] = clean(c["Title"])[:200]
                    phone = clean(c["Phone"]) or clean(c["MobilePhone"])
                    if phone:
                        body["phone"] = phone
                    try:
                        crm_id = self.api.call("POST", "/contacts", body)["id"]
                        self.bump("contact created")
                    except ApiError as e:
                        if e.status == 409 and email:
                            crm_id = self.find_contact(email, f"{first} {last}".strip())
                            if not crm_id:
                                raise
                            self.bump("contact matched existing")
                        else:
                            raise
                    self.state.put("contact", dedupe, crm_id)
                else:
                    self.bump("contact merged (same email)")
            self.state.put("contact", sf_id, crm_id)

        data = {"linkedinUrl": linkedin(c["LinkedIn_URL__c"])}
        data = {k: v for k, v in data.items() if v}
        fields = self.fieldvals("CONTACT", {
            "sf_id": sf_id,
            "department": clean(c["Department"]),
            "management_level": clean(c["Management_Level__c"]),
            "mobile": clean(c["MobilePhone"]),
            "country": clean(c["MailingCountry"]),
            "city": clean(c["MailingCity"]),
            "sf_source": joined(c["Lead_Source__c"], c["LeadSource"], sep=" | "),
        })
        if fields:
            data["fields"] = fields
        if data:
            self.patch("contact", crm_id, data)

    # ---- deals

    def import_deal(self, o):
        sf_id = o["Id"]
        name = clean(o["Name"]) or "Untitled opportunity"
        if o["AccountId"] in self.accounts:
            company_id = self.state.get("company", o["AccountId"])
        else:
            # No Salesforce account: the opportunity name is the company name.
            company_name = re.sub(r"\s+-\s+.*$", "", name).strip() or name
            company_id = self.import_company("opp:" + sf_id, {
                "name": company_name[:200],
                "domain": domain_of(o["Company_Website__c"]),
                "ownerId": None,
            }, {k: v for k, v in {
                "industry": clean(o["Industry__c"]),
                "country": clean(o["Account_Country__c"]),
                "linkedinUrl": linkedin(o["Linkedin_Domain__c"]),
                "fields": self.fieldvals("COMPANY", {
                    "territory": territory(o["Customer_Partner_Location__c"]),
                }) or None,
            }.items() if v})
        if not company_id:
            self.errors.log("deal", sf_id, name, "company", "account was not imported")
            return

        crm_id = self.state.get("deal", sf_id)
        sf_stage = clean(o["StageName"])
        amount = number(o["Amount"]) or number(o["TCV__c"]) or number(o["ARR_Customer__c"])
        if not crm_id:
            owner = self.owner_for(o["Sales_Team__c"], o["Owner__c"]) or self.default_owner
            body = {
                "name": name[:200],
                "companyId": company_id,
                "ownerId": owner,
                "stage": STAGE_MAP.get(sf_stage, "DEMO_BOOKED"),
                "currency": "USD",
            }
            if amount:
                body["amountCents"] = int(round(amount * 100))
            if iso_date(o["CloseDate"]):
                body["expectedCloseDate"] = iso_date(o["CloseDate"])
            crm_id = self.api.call("POST", "/deals", body)["id"]
            self.state.put("deal", sf_id, crm_id)
            self.bump("deal created")

        if not self.state.get("patched", "deal:" + crm_id):
            description = joined(o["Queries_and_Next_Steps__c"], o["NextStep"], o["NotesNew__c"],
                                 o["Notes_Customer_Success__c"])
            data = {"description": description[:20000]} if description else {}
            fields = self.fieldvals("DEAL", {
                "sf_id": sf_id,
                "sf_stage": sf_stage,
                "sf_owner": clean(o["Sales_Team__c"]) or clean(o["Owner__c"]),
                "requirement": clean(o["Requirement__c"]),
                "prospect_interest": clean(o["Prospect_Interest__c"]),
                "competition": clean(o["Competition_Tool__c"]),
                "solution_engineer": clean(o["Solution_Engineer_Contact__c"]),
                "lead_generated_by": joined(o["Lead_Generated_By__c"], o["Lead_Gen_Contact__c"], sep=" | "),
                "potential": clean(o["Potential__c"]) or clean(o["Deal_Reg_Potential__c"]),
                "bant_score": clean(o["BANT_Score__c"]),
                "mrr": number(o["MRR__c"]),
                "arr": number(o["ARR_Customer__c"]) or number(o["ARR__c"]),
                "first_demo_date": iso_date(o["First_Demo_Date__c"]),
                "sf_created": iso_date(o["CreatedDate"]),
            })
            if fields:
                data["fields"] = fields
            if data:
                self.patch("deal", crm_id, data)

        # People on the deal: the Salesforce contact lookups, when that contact
        # works at the same company.
        role = clean(o["Contact_Role__c"])[:80] or None
        for sf_contact in {clean(o["ContactId"]), clean(o["Contact_Name__c"])} - {""}:
            link_key = f"{sf_id}:{sf_contact}"
            contact_id = self.state.get("contact", sf_contact)
            if not contact_id or self.state.get("linked", link_key):
                continue
            try:
                self.api.call("POST", f"/deals/{crm_id}/contacts", {"contactId": contact_id, "role": role})
                self.state.put("linked", link_key, True)
                self.bump("deal contact linked")
            except ApiError as e:
                self.errors.log("deal", sf_id, name, "link contact", e)

    # ---- driver

    def run_pool(self, label, items, fn, describe):
        total = len(items)
        done = 0
        started = time.time()
        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            futures = {pool.submit(fn, item): item for item in items}
            for fut in as_completed(futures):
                item = futures[fut]
                try:
                    fut.result()
                except Exception as e:  # noqa: BLE001 - every failure is logged and skipped
                    sf_id, name = describe(item)
                    self.errors.log(label, sf_id, name, "create", e)
                done += 1
                if done % 100 == 0 or done == total:
                    rate = done / max(1, time.time() - started)
                    print(f"  {label}: {done}/{total}  ({rate:.1f}/s, errors so far {self.errors.count})", flush=True)
        self.state.save()

    def dry_run(self):
        from collections import Counter
        stages = Counter(STAGE_MAP.get(clean(o["StageName"]), "DEMO_BOOKED") for o in self.opps)
        domains = Counter(domain_of(self.accounts[a]["Website"]) for a in self.account_ids)
        names = {u["id"]: u["name"] for u in self.users}
        owners = Counter(
            names[self.owner_for(o["Sales_Team__c"], o["Owner__c"]) or self.default_owner]
            for o in self.opps)
        bad_email = sum(1 for c in self.contacts if clean(c["Email"]) and not EMAIL_RE.match(clean(c["Email"]).lower()))
        print("deal stages:", dict(stages))
        print("deal owners:", dict(owners))
        print("accounts with no usable domain:", domains[None])
        print("accounts sharing a domain with another:", sum(n - 1 for d, n in domains.items() if d and n > 1))
        print("contacts with an invalid email (dropped):", bad_email)
        print("opportunities with no account (company made from opp name):",
              sum(1 for o in self.opps if o["AccountId"] not in self.accounts))
        print("fields:", json.dumps(self.fields, indent=1))

    def run(self):
        self.load()
        self.load_users()
        self.ensure_fields()
        if self.args.dry_run:
            self.dry_run()
            return

        accounts = [self.accounts[i] for i in sorted(self.account_ids)]
        print("1/3 companies")
        self.run_pool("company", accounts,
                      lambda a: self.import_company(a["Id"], *self.company_payloads(a)),
                      lambda a: (a["Id"], a["Name"]))
        print("2/3 contacts")
        self.run_pool("contact", self.contacts, self.import_contact, lambda c: (c["Id"], c["Name"]))
        print("3/3 deals")
        self.run_pool("deal", self.opps, self.import_deal, lambda o: (o["Id"], o["Name"]))

        print("\nresult:")
        for k in sorted(self.stats):
            print(f"  {k}: {self.stats[k]}")
        print(f"  errors: {self.errors.count}  (see {ERRORS_PATH})")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--scope", choices=["pipeline", "all"], default="pipeline")
    p.add_argument("--limit", type=int, default=0, help="pilot: only this many opportunities")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    if not KEY:
        sys.exit("Set CRM_API_KEY first.")
    if not DEFAULT_OWNER_EMAIL:
        sys.exit("Set CRM_DEFAULT_OWNER_EMAIL to the CRM user who owns unmatched deals.")
    Importer(args).run()


if __name__ == "__main__":
    main()
