#!/usr/bin/env python3
"""
Generate a small set of folder index READMEs under docs/ so the tree is
crawlable without opening every file.

Scope, on purpose, is narrow to avoid clutter:
  * docs/README.md            - master index of the top-level sections
  * docs/<section>/README.md  - one per top-level folder that directly holds
                                markdown pages (how-to, use-cases, etc.)

It does NOT touch image or asset folders, and it does NOT descend into nested
subfolders. Each README lists the markdown pages in that one folder, with the
description taken from each page's front matter.

The generator is self-cleaning: any README it previously wrote (marked with the
comment below) that now falls outside this scope is removed. Hand-written
READMEs, which lack the marker, are left alone.

The READMEs are kept out of the published MkDocs site (exclude_docs in
mkdocs.yml and the README skip in hooks/copy_md_source.py).

Run manually:   python scripts/gen_docs_readmes.py
Runs on commit via .githooks/pre-commit.
"""

import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS_DIR = os.path.join(REPO_ROOT, "docs")

MARKER = "<!-- AUTO-GENERATED folder index. Do not edit by hand. " \
         "Regenerated by scripts/gen_docs_readmes.py (runs on commit). -->"

SKIP_DIRS = {"__pycache__"}
README_NAME = "README.md"

SECTION_ABOUT = {
    "how-to": "Task-oriented how-to guides: onboarding, configuration, and "
              "step-by-step procedures across every AccuKnox module.",
    "use-cases": "Use-case walkthroughs that show AccuKnox capabilities applied "
                 "to real security scenarios.",
    "integrations": "Integration guides for CI/CD, SIEM, ticketing, registries, "
                    "SSO, AI gateways, K8s management, and notifications.",
    "getting-started": "Getting-started material: installation, on-prem "
                       "deployment, architecture, and release notes.",
    "faqs": "Frequently asked questions grouped by product area.",
    "support-matrix": "Supported platforms, versions, cloud regions, and "
                      "configurations for each module.",
    "resources": "Reference resources: architecture, troubleshooting, pricing, "
                 "manuals, glossary, and release notes.",
    "knoxctl": "knoxctl CLI reference: configuration, commands, and usage.",
    "introduction": "Introductory material and open-source vs enterprise "
                    "comparison.",
}


def clean_text(text):
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"[*_`#>]", "", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def describe_markdown(path):
    try:
        with open(path, encoding="utf-8") as fh:
            raw = fh.read()
    except OSError:
        return ""
    title = desc = None
    body = raw
    fm = re.match(r"^---\n(.*?)\n---\n", raw, re.S)
    if fm:
        block = fm.group(1)
        dm = re.search(r"^description:\s*(.+)$", block, re.M)
        tm = re.search(r"^title:\s*(.+)$", block, re.M)
        if dm:
            desc = dm.group(1).strip().strip("\"'")
        if tm:
            title = tm.group(1).strip().strip("\"'")
        body = raw[fm.end():]
    if not desc:
        for line in body.splitlines():
            s = line.strip()
            if not s or s.startswith(("#", "<", "!!!", "::", "|", "---", "```",
                                      "- ", "* ", "=== ", "    ")):
                continue
            desc = s
            break
    chosen = clean_text(desc or title or "")
    if len(chosen) > 160:
        chosen = chosen[:157].rstrip() + "..."
    return chosen


def has_marker(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return MARKER in fh.read(len(MARKER) + 4)
    except OSError:
        return False


def direct_md(abs_dir):
    return sorted(f for f in os.listdir(abs_dir)
                  if f.endswith(".md") and f != README_NAME
                  and os.path.isfile(os.path.join(abs_dir, f)))


def has_md_recursive(abs_dir):
    for _root, _dirs, files in os.walk(abs_dir):
        if any(f.endswith(".md") and f != README_NAME for f in files):
            return True
    return False


def link(name):
    return name.replace(" ", "%20")


def write_if_changed(target, content, changed):
    old = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as fh:
            old = fh.read()
    if old != content:
        with open(target, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        changed.append(os.path.relpath(target, REPO_ROOT).replace(os.sep, "/"))


def build_section_readme(abs_dir, section):
    md_files = direct_md(abs_dir)
    about = SECTION_ABOUT.get(section,
                              "Pages in the %s section." % section)
    lines = [MARKER, "", "# `%s/` — folder index" % section, "", about, "",
             "## Pages", "", "| File | What it covers |", "|---|---|"]
    for f in md_files:
        desc = (describe_markdown(os.path.join(abs_dir, f)) or "—").replace("|", "\\|")
        lines.append("| [%s](%s) | %s |" % (f, link(f), desc))
    # note nested folders that contain more pages, without indexing them
    nested = []
    for d in sorted(os.listdir(abs_dir)):
        full = os.path.join(abs_dir, d)
        if os.path.isdir(full) and d not in SKIP_DIRS and not d.startswith("."):
            if has_md_recursive(full):
                nested.append(d)
    if nested:
        lines += ["", "## Subfolders with more pages", ""]
        for d in nested:
            lines.append("- `%s/`" % d)
    return "\n".join(lines).rstrip() + "\n"


def build_root_readme(sections, root_pages):
    lines = [MARKER, "", "# `docs/` — folder index", "",
             "Root of the AccuKnox help documentation. The top-level sections "
             "below each have their own folder index.", "",
             "## Sections", "", "| Section | What it covers |", "|---|---|"]
    for s in sections:
        about = SECTION_ABOUT.get(s, "Pages in the %s section." % s)
        lines.append("| [%s/](%s/README.md) | %s |" % (s, link(s), about))
    if root_pages:
        lines += ["", "## Root pages", "", "| File | What it covers |", "|---|---|"]
        for f in root_pages:
            desc = (describe_markdown(os.path.join(DOCS_DIR, f)) or "—").replace("|", "\\|")
            lines.append("| [%s](%s) | %s |" % (f, link(f), desc))
    return "\n".join(lines).rstrip() + "\n"


def main():
    changed, removed = [], []

    # top-level folders that directly contain markdown pages
    sections = []
    for name in sorted(os.listdir(DOCS_DIR)):
        full = os.path.join(DOCS_DIR, name)
        if os.path.isdir(full) and name not in SKIP_DIRS \
                and not name.startswith(".") and direct_md(full):
            sections.append(name)

    allowed = {os.path.join(DOCS_DIR, README_NAME)}
    allowed |= {os.path.join(DOCS_DIR, s, README_NAME) for s in sections}

    # 1. remove any auto-generated README that is now out of scope
    for root, dirs, files in os.walk(DOCS_DIR):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        if README_NAME in files:
            path = os.path.join(root, README_NAME)
            if path not in allowed and has_marker(path):
                os.remove(path)
                removed.append(os.path.relpath(path, REPO_ROOT).replace(os.sep, "/"))

    # 2. generate the in-scope READMEs
    for s in sections:
        write_if_changed(os.path.join(DOCS_DIR, s, README_NAME),
                         build_section_readme(os.path.join(DOCS_DIR, s), s),
                         changed)
    root_pages = direct_md(DOCS_DIR)
    write_if_changed(os.path.join(DOCS_DIR, README_NAME),
                     build_root_readme(sections, root_pages), changed)

    for p in changed:
        print("updated", p)
    for p in removed:
        print("removed", p)
    sys.stderr.write("gen_docs_readmes: %d updated, %d removed\n"
                     % (len(changed), len(removed)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
